### ISSUE TITLE
Splitted CSV files does not container header row

### ISSUE THREAD

**Issue by runlevel5** [PerformanceHorizonGroup/csv-split#1]
Task: Splitting a big CSV with first row as header into many small files
Expected: Split files injects with header
Result: Split file does not have header

**Comment by michael-grunder** [comment]
Hey,

Currently csv-split doesn't consider headers at all.  We could add an option to treat the first line as such and inject into each split file.  Would something like that work?

Cheers,
Mike

**Comment by runlevel5** [comment]
@michael-grunder yeah, a flag option would be great, for the time being I am doing this step via bash with:

```
# extract first row (the header)
head -n 1 file.csv > header.csv

# create a temporary file containing the content without
# the header:
tail -n +2 file.csv > content.csv

# run the csvsplit
csv-split -n 10000 content.csv output/

for f in output/*; do cat header.csv $f > $f.csv; rm $f; done;
```

Cheers

**Comment by michael-grunder** [comment]
Nice bash work.  I always love a good bash solution even though I'm somewhat terrible at shell scripting.  :)

I have csv-split injecting headers, but I was thinking.  Should it include the header row in it's rowcount or just include data rows.  I sort of think it should discount the header as it's not actual data, but it could always be an option to the --header argument (e.g. header=1 to count the header as a data row, and default to not).

**Comment by runlevel5** [comment]
@michael-grunder nice work. imho, row count should disregard the header row
