### ISSUE TITLE
Add versioning

### ISSUE THREAD

**Issue by runlevel5** [PerformanceHorizonGroup/csv-split#3]
Can you please add version to this app? Cheers

Please also tag this release on GitHub.

**Comment by michael-grunder** [comment]
I can tag it in GitHub, but what specifically do you need in terms of versioning.  Right now I just use a constant which is printed if you do `csv-split --version`

**Comment by runlevel5** [comment]
it'd be great if you could tag it 0.1.0. This is for Homebrew formula that I am cooking which requires a release from github repo

**Comment by michael-grunder** [comment]
Upped a tagged version (0.1.1 for the header feature).

Cheers
Mike
