### ISSUE TITLE
Add configure

### ISSUE THREAD

**Issue by runlevel5** [PerformanceHorizonGroup/csv-split#4]
Is there any chance if you could add `configure` script? The homebrew guy request that we should be able to install to a prefix if needed

**Comment by michael-grunder** [comment]
Yeah this can be accomplished.  Honestly I'm not great with autoconf but it doesn't look too involved.  It's actually a good idea to do this if anyone other than us will be using the tool. 

Cheers
Mike

**Comment by runlevel5** [comment]
@michael-grunder sorry I could not help much here, I am no good with autoconf nor C.

**Comment by runlevel5** [comment]
@michael-grunder  any chance you could do it? Else I think I would ask someone with exp and do this for you

**Comment by michael-grunder** [comment]
Hey,

Work has been crazy.  I do plan on taking a look at this but I'm always happy for others to help.  Open source ftw!  :)

Cheers,
Mike
